apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/upendrasahu/pythonapp-8838:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/upendrasahu/pythonapp-8838:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: pythonapp-8838
        chartPath: charts/pythonapp-8838
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/upendrasahu/pythonapp-8838"
          image.tag: "{{.DIGEST_HEX}}"
